---

name: Deploy streaming

on: 
  push: 
    branches: 
      - main

jobs:
  deploy-vkit: 
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@main

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: install jekyll
        run: gem install bundler jekyll

      - name: install s3_website
        run: gem install s3_website

      - name: jekyll build
        run: jekyll build

      - name: sync to s3
        run: s3_website push
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}







